/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.*;
import DAO.ConteudoDAO;
import java.awt.event.MouseAdapter;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import static java.util.stream.Collectors.toList;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro Gomes
 */
public class ShowForm extends javax.swing.JFrame {
    private Content c;
   
    /**
     * Creates new form UploadForm
     */
    public ShowForm(Content x) {
        c = x;
        
        initComponents();
        loadTable();
        
    }

    
    public void loadTable(){
        int i= 0;
        MediaCenter mc = MediaCenter.getInstance();
        
        if(c instanceof MusicContent){
            List<Categoria> lista = mc.getAllCategorias().stream().collect(toList());
            List<String> s = new ArrayList();
            for(Categoria c : lista){
                s.add(c.getNome());
            }
            loadTable(s,mc,lista);
        }
        if(c instanceof VideoContent){
            List<Categoria> lista = mc.getALLCategoriasVideo().stream().collect(toList());
            List<String> s = new ArrayList();
            for(Categoria c : lista){
                s.add(c.getNome());
            }
            loadTable(s,mc,lista);
        
        }
        
    
    }
    
    
    private void loadTable(List<String> s,MediaCenter mc,List<Categoria> lista){
        int i = 0;
        DefaultTableModel model = (DefaultTableModel) this.tabela.getModel();
        
        int tmp = s.size();
        while(i<tmp){
            model.addRow(s.stream().toArray());
            if(tmp> 8)s =s.subList(8,s.size());
            i+=8;
        }
        this.tabela.addMouseListener(new MouseAdapter() {
             @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                    int column = tabela.columnAtPoint(evt.getPoint());
                    int row = tabela.rowAtPoint(evt.getPoint());
                    if(column>= 0 && row >= 0  ) {
                        mc.changemyCategoria(c,lista.get(row*8 +column));
                        
                    }
                    
              
        }
        });
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        musicTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        musicTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nome", "Artista", "Categoria", "Duracao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(musicTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Artista", "Categoria", "Duração", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane3.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setHeaderValue("Nome");
            tabela.getColumnModel().getColumn(1).setHeaderValue("Artista");
            tabela.getColumnModel().getColumn(2).setHeaderValue("Categoria");
            tabela.getColumnModel().getColumn(3).setHeaderValue("Duração");
            tabela.getColumnModel().getColumn(4).setHeaderValue("Title 5");
            tabela.getColumnModel().getColumn(5).setHeaderValue("Title 6");
            tabela.getColumnModel().getColumn(6).setHeaderValue("Title 7");
            tabela.getColumnModel().getColumn(7).setHeaderValue("Title 8");
        }

        jButton1.setText("dispose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowForm(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable musicTable;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
